#pragma once

// CPython's NB_* argument values used by BINARY_OP. Keeping these symbolic
// prevents version adapters and tests from embedding unexplained literals.
#define CPYGRAPH_BINARY_OP_ADD 0
#define CPYGRAPH_BINARY_OP_AND 1
#define CPYGRAPH_BINARY_OP_FLOOR_DIVIDE 2
#define CPYGRAPH_BINARY_OP_LSHIFT 3
#define CPYGRAPH_BINARY_OP_MATRIX_MULTIPLY 4
#define CPYGRAPH_BINARY_OP_MULTIPLY 5
#define CPYGRAPH_BINARY_OP_REMAINDER 6
#define CPYGRAPH_BINARY_OP_OR 7
#define CPYGRAPH_BINARY_OP_POWER 8
#define CPYGRAPH_BINARY_OP_RSHIFT 9
#define CPYGRAPH_BINARY_OP_SUBTRACT 10
#define CPYGRAPH_BINARY_OP_TRUE_DIVIDE 11
#define CPYGRAPH_BINARY_OP_XOR 12
#define CPYGRAPH_BINARY_OP_INPLACE_ADD 13
#define CPYGRAPH_BINARY_OP_INPLACE_AND 14
#define CPYGRAPH_BINARY_OP_INPLACE_FLOOR_DIVIDE 15
#define CPYGRAPH_BINARY_OP_INPLACE_LSHIFT 16
#define CPYGRAPH_BINARY_OP_INPLACE_MATRIX_MULTIPLY 17
#define CPYGRAPH_BINARY_OP_INPLACE_MULTIPLY 18
#define CPYGRAPH_BINARY_OP_INPLACE_REMAINDER 19
#define CPYGRAPH_BINARY_OP_INPLACE_OR 20
#define CPYGRAPH_BINARY_OP_INPLACE_POWER 21
#define CPYGRAPH_BINARY_OP_INPLACE_RSHIFT 22
#define CPYGRAPH_BINARY_OP_INPLACE_SUBTRACT 23
#define CPYGRAPH_BINARY_OP_INPLACE_TRUE_DIVIDE 24
#define CPYGRAPH_BINARY_OP_INPLACE_XOR 25
#define CPYGRAPH_BINARY_OP_SUBSCRIPT 26
